### PR TITLE
Ansible-stuck-issue

### PR DESCRIPTION
**Pull request by adriannavarrobetrian**
(_gwright99 edit_): Proposed fix for issue: https://github.com/seqeralabs/cx-field-tools-installer/issues/26

### CODE REVIEW

**Comment by gwright99** [comment]
@adriannavarrobetrian -- What tests have you run to confirm the behaviour of the counter logic?

- Positive case should be pretty easy (_i.e. run the installer and if it doesn't fail, it means it works).
- Negative case: How are making it so that the call to pypi fails?

**Comment by adriannavarrobetrian** [comment]
@gwright99 I've tested both the positive case and the negative one.
For the negative I've used a bogus endpoint for pip and it fails and exists the terraform setup with the error 
"Failed to download file after 10 attempts."

**Comment by adriannavarrobetrian** [comment]
@gwright99 what do you think about add tflint and tfsec steps to the terraform code? There are a couple of vulnerabilities on it.

```bash
❯ tflint
21 issue(s) found:
```

```bash
 ❯ tflint
  57 passed, 27 potential problem(s) detected.
```

**Comment by gwright99** [comment]
> @gwright99 what do you think about adding tflint and tfsec steps to the terraform code? There are a couple of vulnerabilities on it.
> 
> ```shell
> ❯ tflint
> 21 issue(s) found:
> ```
> 
> ```shell
>  ❯ tflint
>   57 passed, 27 potential problem(s) detected.
> ```

I'm supportive in theory. Want to book me for a quick discussion, then we can decide?

**Review by adriannavarrobetrian — COMMENTED** [review]
Looks good

**Review by gwright99 — APPROVED** [review]
Approved. 
Ran into the pypi problem again during migrate-db patch testing so we need this resilience.

**Pull request merged**
