### PR TITLE
Changed ssh_config chmod to 644

### PR DESCRIPTION
**Pull request by gwright99**

### CODE REVIEW

**Comment by gwright99** [comment]
@adriannavarrobetrian @markpanganiban -- can one of you confirm the `ssh_config` update still works for you too please? Thanks!

**Review by adriannavarrobetrian — APPROVED** [review]
I was gonna do this one...:)

**Comment by adriannavarrobetrian** [comment]
it works

**Comment by gwright99** [comment]
Could have deleted my branch and used your own :D

**Pull request merged**
