### PR TITLE
Gwright99/31-implement-python-verification

### PR DESCRIPTION
**Pull request by adriannavarrobetrian**

### CODE REVIEW

**Comment by adriannavarrobetrian** [comment]
Several concerns about the script.

1. I think all removal of comments should be in another script, it would be much more readable and organized. Are you sure a simple sed wouldn't work? :)
2. The way python gets the AWS configuration is machine specific, this should run always on a pipeline ideally. We should think how to standardize it so that it works everywhere otherwise.
3. Should it be a githook? Maybe a script call in a makefile before terraform plan it's simpler?
4. Should we work before in a simple standard pipeline (Atlantis or whatever) before adding this script?
...

**Comment by gwright99** [comment]
Thoughts:

1. Comment extraction was moved to a separate module to keep the main script cleaner. I think we should keep the two mechanisms together because the edge-cases (jamming together a multi-line entry) will break if you don't rip out interspersed or inline comments. 

    i. I added a comment agreeing that roll-your-own-parser is normally dumb. I'd prefer to use `sed` but - prior to you joining - we had several issues where MacOS `sed` did not behave the same way as Windows/Linux `sed`. Using a pure Python solution means we don't need to think about OS mismatches or include this as a test case.  I've kept the suggested `sed` command in the script anyways in case we change our mind / get feedback from the field that the current solution is stupid (_I could be convinced_).

3.  Not sure I understand the `boto3` concern. Agree that it's AWS-specific right now, but that's the only environment we support right now (TBD if we do the same for Azure/GCP). Subnet mismatches are pretty common and we have at least a few examples of clients trying to work with an existing VPC who encountered subnet configuration errors. 

I'm happy to make this a bit more agnostic if we think it's easy to do, but don't want to over-optimize/abstract too early. Let's discuss.

4. The code is in a `.githook` folder because it needs to be there to run a `pre-commit` action. I don't think its placement in the project precludes a `Make` file from calling it. I was thinking checks happen in two places:
    1. Via `Make` file before deployment (_i.e. I'll often run a configuration **prior** to commiting_).
    2. A secondary check in the `pre-commit` phase (_to ensure a misconfiguration wasn't introduced between the deployment test and submission to the git repo).
 
5. Do you think you can start implementing an Atlantis branch in parallel to this work. Working concurrently would be beneficial, particuarly if you can do your work if I promise to not change the script entrypoint being `.githooks/check_configuration.py`

**Comment by adriannavarrobetrian** [comment]
1. Fine by me.
2. Oh, you added a variable for the AWS profile, I think I saw a hardcoded profile there... never mind.
3. Ok, we can call it from both places, that's fine.
4. Yes:), I'll start looking at https://www.runatlantis.io

**Comment by gwright99** [comment]
Makefile and pre-commit mechanism working:

image

image

**Comment by gwright99** [comment]
@adriannavarrobetrian -- seeing as I wrote the code in this PR, it would be a little self-serving of me to approve it too. I can't assign you as a Reviewer since you've opened the PR, so I'm tagging @markpanganiban for the sanity check.

**Comment by gwright99** [comment]
@markpanganiban I'll update the README, but you need the following commands to test:

1. *pre-commit hook*: 
    1. In the root of the repo, execute: `git config core.hooksPath .githooks`
    2. Add a file to the branch and then try to commit. 
    You should see the Python script fire.
    
2. *Validation before TF execution*:
   1. In the root of the repo, type: `make plan`. 
   You should see the Python script fire and then cascade into a `terraform plan` if all checks are passed.

**Review by markpanganiban — APPROVED** [review]
lgtm!

**Pull request merged**
