### PR TITLE
Support CodeCommit in Seqerakit flow

### PR DESCRIPTION
**Pull request by gwright99**
Implements [https://github.com/seqeralabs/cx-field-tools-installer/issues/20](https://github.com/seqeralabs/cx-field-tools-installer/issues/20)

### CODE REVIEW

**Comment by gwright99** [comment]
As per comment in source Issue, this one ended up being more complex than expected (_see number of files changed_).

Also includes a fix for [a commit](https://github.com/seqeralabs/cx-field-tools-installer/commit/94301d435e29bb613ad5f2e8a784c6dc843cb608) I made a few days ago that broke the Groundswell fix.

**Comment by gwright99** [comment]
@markpanganiban @adriannavarrobetrian -- happy with what's here or do I need to make any changes?

**Comment by adriannavarrobetrian** [comment]
How can we test it? Too many changes to understand what's going on... 😅

**Comment by gwright99** [comment]
> How can we test it? Too many changes to understand what's going on... 😅

1. Existing flow:
    1. Use your existing `tfvars` file.
    2. Add  `seqerakit_flag_credential_create_codecommit = false` to `tfvars`
    3. Run project and confirm it executes

2. New flow:
    1. Set ``seqerakit_flag_credential_create_codecommit = true` in tfvars.
    2. Add codecommit-related keys into the seqerakit secret in SSM (you can get the User keys for my configuration in SSM)
    3. Run project and confirm that:
        1. CodeCommit credential ends up in the Workspace.
        2. CodeCommit pipeline ends up in the Workspace.

Simple enough? Most of the changes are behind-the-scenes mechanism to make sure flow 1 still works and makes flow 2 possible.

**Comment by adriannavarrobetrian** [comment]
Screenshot 2024-05-09 at 19 19 37

**Comment by markpanganiban** [comment]
Good to merge!

There was en error on my initial testing due to confusion on the codecommit region. The value should be the full region instead of the AZ ie, `https://git-codecommit.us-east-1.amazonaws.com`

image

**Review by markpanganiban — APPROVED** [review]

**Pull request merged**
