### PR TITLE
Gwright99/issue 28 fix migrate db

### PR DESCRIPTION
**Pull request by gwright99**
Fixes bug where using a `tower_container_version` < 23.4.1 would result in a deployment error since the `migrate-db` container is only available for Seqera Platform 23.4.1+

### CODE REVIEW

**Comment by gwright99** [comment]
@adriannavarrobetrian -- testing results:

image

image

**Review by adriannavarrobetrian — APPROVED** [review]

**Comment by gwright99** [comment]
@adriannavarrobetrian -- I discovered the master branch logic didn't handle things so well when I tried to run 23.1.3.

While I think it's unlikely a brand new installation is going to install an older version of Tower, the extra checks and logic is useful for us to be able to spin up instances that match client installations.

I have no merged the approved changes yet, and instead chose to push another commit. Let's have a chat early next week to figure out how to review this again (please)?

**Comment by gwright99** [comment]
@adriannavarrobetrian -- push several changes in this PR. I could have separated some of them into a separate PR but the changes in this one would need to be coordinated with the other one so I just kept them all together.

Modifications:

- Some features break when you go back to an older version (e.g. SES IAM only available in 23.2+). Added checks to make sure - even if flag is set - it's set for a version where it will actually work. Not doing this results in an app that implodes on boot.

- Permissions were missing a bunch of entries. The IAMlive proxy was a good start but missed a bunch of stuff. I ended up assuming a limited AWS role and ran a bunch of deployments to see where it failed. Docs updated with policy that eventually allowed me to do a true e2e deployment with Elasticache and RDS.

- Like the pypi race-condition, I noticed first-time SSH could sometimes break (i.e. TF tries to connect before the EC2 is ready). This resulted in a failure to deploy files and required another `terraform apply`. I added in a retry loop for more resilience.

- Noticed that I hadn't harmonize the `ssh_config` aliases. This broke when I stopped using EICE (to speed up testing). Fixed.

In addition to your ideas about tflint/tfsec, we should think about how best to test this app more effectively. I understand we are going to need to alwasy do real-world runs, but this kind of testing is starting to chew up hours (but we see what happens if there's shirking on testing too). TBD.

**Review by adriannavarrobetrian — APPROVED** [review]
Looks fine to me. I´ve deployed it also and no issues.

**Pull request merged**
