### PR TITLE
Support terraform init on macos

### PR DESCRIPTION
**Pull request by BooleanCat**
Note: contains formats from `terraform fmt`.

* Use templatefile builtin rather than from unsupported provider
* Commit the lockfile to freeze provider versions

### CODE REVIEW

**Comment by gwright99** [comment]
Hi @BooleanCat,

Thanks for the PRs! My colleague and I will be conducting some testing for the PR this afternoon. For our benefit and additional context for any other readers, could kindly advise:

1. What Mac chip you run your Terraform on (e.g. M1/M2/M3)?

2. How you installed the Terraform binary (official Terraform, Homebrew, tfenv, etc)?

3. What drove you to remove the `data` resources and move the logic to local variables instead?

**Comment by BooleanCat** [comment]
1.  M2
2. brew install terraform
3. The templatefile provider doesn't compile on macos ARM chips. So I've replaced it with the built-in templatefile and stopped using the provider.

**Comment by gwright99** [comment]
PR works fine on WSL2 (Intel) chip. Waiting for a colleague's feedback re: testing on M2 silicon. If that passes, we'll merge the PR and issue a new Release.

**Review by gwright99 — APPROVED** [review]
PR passed testing on both WSL2 and Mac silicon. Approving and merging.

**Pull request merged**
