### PR TITLE
Gwright99/31 remove checks from tf

### PR DESCRIPTION
**Pull request by gwright99**
Implements [https://github.com/seqeralabs/cx-field-tools-installer/issues/35](https://github.com/seqeralabs/cx-field-tools-installer/issues/35).

Removed several checks added in [PR #29 ](https://github.com/seqeralabs/cx-field-tools-installer/pull/29/files)

### CODE REVIEW

**Comment by gwright99** [comment]
I managed to remove most of the checks but had to keep migrate-db. 
Also found a bug in the home-rolled parser (oops!)

**Comment by gwright99** [comment]
It looks like you can't attach a TF `lifecycle` object to a module (_see [Add support for lifecycle meta-argument in modules](https://github.com/hashicorp/terraform/issues/27360)_).

There is a workaround proposed in the thread [here](https://github.com/hashicorp/terraform/issues/27360#issuecomment-957294607), but this won't work either since the lifecycle bool needs to be a literal and we need to be able to use the tfvars variable.

I've decided to duplicate the model we use to check variables prior to deployment: there's now another script in `.githooks` which is invoked prior to destroy (_if you run `make destroy`_). Single check for now: if the tfvars key `db_deletion_protection` is `true`, this means the user hasn't updated the resource in place to strip deletion protection. The process will stop and they'll be told to patch the RDS instance before trying again.

image

**Comment by gwright99** [comment]
Ok, enough work has been done on this that it is time to merge and release.

**Review by adriannavarrobetrian — APPROVED** [review]
Looks good. Can we have smaller PRs from now on please?... :)

**Comment by gwright99** [comment]
@markpanganiban -- were you able to get this working too? If yes, I'll merge once I get the checkmark. If not, I'll carve out some time tomorrow to troubleshoot. You are a good test-case since you are leapfrogging from an older implementation.

**Review by markpanganiban — APPROVED** [review]
LGTM!

As discussed with Graham, there was an error on my old tfvars which is causing the initial plan to fail.

**Pull request merged**
