### PR TITLE
Add admin endpoint

### PR DESCRIPTION
**Pull request by adriannavarrobetrian**

### CODE REVIEW

**Review by adriannavarrobetrian — COMMENTED** [review]
I still don't have answer about proper login when clicking on the email link, but this creates the admin endpoint

**Comment by adriannavarrobetrian** [comment]
Also, I wanted to apply a `terraform fmt` but it made the PR confusing. I'll create a PR with that.

**Comment by gwright99** [comment]
@adriannavarrobetrian -- what's the status of this PR? Still want to merge it?

**Comment by adriannavarrobetrian** [comment]
It looks like the admin.TOWER_URL endpoint was deprecated a long time ago, so I don't think it makes sense to add it.

**Comment by gwright99** [comment]
Closing this PR to declutter.

**Pull request closed without merging**
